# Generated by Django 2.2.1 on 2019-05-05 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('sales_type', models.CharField(choices=[('BY', 'Buy'), ('RT', 'Rent')], max_length=2)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('psm', models.IntegerField(blank=True)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('listing_type', models.CharField(choices=[('Residential', (('CD', 'Condominium'), ('DH', 'Detached Home'), ('AP', 'Apartment'))), ('Commercial', (('CB', 'Commercial Building'), ('OB', 'Office Building'), ('HT', 'Hotel'))), ('LN', 'Land'), ('ID', 'Industrial')], max_length=2)),
                ('garage', models.IntegerField(blank=True, default=0)),
                ('util_space', models.IntegerField(blank=True)),
                ('sqmt', models.IntegerField()),
                ('furnishing', models.CharField(max_length=100)),
                ('floor', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('tenure', models.CharField(choices=[('FH', 'Freehold'), ('LH', 'Leasehold')], max_length=2)),
                ('developer', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_7', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_8', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_9', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_10', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_11', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_12', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_13', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_14', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_15', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_16', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_17', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_18', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_19', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_20', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_21', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_22', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_23', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_24', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_25', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_26', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_27', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_28', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_29', models.ImageField(blank=True, upload_to='photos/')),
                ('photo_30', models.ImageField(blank=True, upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
