# Generated by Django 2.2.1 on 2019-05-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190505_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('Residential', (('CD', 'Condominium'), ('DH', 'Detached Home'), ('AP', 'Townhome'))), ('Commercial', (('CB', 'Commercial Building'), ('OB', 'Office Building'), ('HT', 'Hotel'))), ('LN', 'Land'), ('ID', 'Industrial')], max_length=2),
        ),
    ]
